/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as PublicationSlugRouteImport } from './routes/publication.$slug'
import { Route as WriterAnalyticsRouteImport } from './routes/writer.analytics'
import { Route as WriterArticlesRouteImport } from './routes/writer.articles'
import { Route as WriterDashboardRouteImport } from './routes/writer.dashboard'
import { Route as WriterDraftsRouteImport } from './routes/writer.drafts'
import { Route as WriterEditorRouteImport } from './routes/writer.editor'
import { Route as WriterFollowersRouteImport } from './routes/writer.followers'
import { Route as PublicationSlugAnalyticsRouteImport } from './routes/publication.$slug.analytics'
import { Route as PublicationSlugArticlesRouteImport } from './routes/publication.$slug.articles'
import { Route as PublicationSlugSubscribersRouteImport } from './routes/publication.$slug.subscribers'
import { Route as PublicationSlugWritersRouteImport } from './routes/publication.$slug.writers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const PublicationSlugRoute = PublicationSlugRouteImport.update({
  id: '/publication/$slug',
  path: '/publication/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterAnalyticsRoute = WriterAnalyticsRouteImport.update({
  id: '/writer/analytics',
  path: '/writer/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterArticlesRoute = WriterArticlesRouteImport.update({
  id: '/writer/articles',
  path: '/writer/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterDashboardRoute = WriterDashboardRouteImport.update({
  id: '/writer/dashboard',
  path: '/writer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterDraftsRoute = WriterDraftsRouteImport.update({
  id: '/writer/drafts',
  path: '/writer/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterEditorRoute = WriterEditorRouteImport.update({
  id: '/writer/editor',
  path: '/writer/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterFollowersRoute = WriterFollowersRouteImport.update({
  id: '/writer/followers',
  path: '/writer/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationSlugAnalyticsRoute =
  PublicationSlugAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => PublicationSlugRoute,
  } as any)
const PublicationSlugArticlesRoute = PublicationSlugArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => PublicationSlugRoute,
} as any)
const PublicationSlugSubscribersRoute =
  PublicationSlugSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => PublicationSlugRoute,
  } as any)
const PublicationSlugWritersRoute = PublicationSlugWritersRouteImport.update({
  id: '/writers',
  path: '/writers',
  getParentRoute: () => PublicationSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookmarks': typeof BookmarksRoute
  '/feed': typeof FeedRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/publication/$slug': typeof PublicationSlugRouteWithChildren
  '/writer/analytics': typeof WriterAnalyticsRoute
  '/writer/articles': typeof WriterArticlesRoute
  '/writer/dashboard': typeof WriterDashboardRoute
  '/writer/drafts': typeof WriterDraftsRoute
  '/writer/editor': typeof WriterEditorRoute
  '/writer/followers': typeof WriterFollowersRoute
  '/publication/$slug/analytics': typeof PublicationSlugAnalyticsRoute
  '/publication/$slug/articles': typeof PublicationSlugArticlesRoute
  '/publication/$slug/subscribers': typeof PublicationSlugSubscribersRoute
  '/publication/$slug/writers': typeof PublicationSlugWritersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookmarks': typeof BookmarksRoute
  '/feed': typeof FeedRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/publication/$slug': typeof PublicationSlugRouteWithChildren
  '/writer/analytics': typeof WriterAnalyticsRoute
  '/writer/articles': typeof WriterArticlesRoute
  '/writer/dashboard': typeof WriterDashboardRoute
  '/writer/drafts': typeof WriterDraftsRoute
  '/writer/editor': typeof WriterEditorRoute
  '/writer/followers': typeof WriterFollowersRoute
  '/publication/$slug/analytics': typeof PublicationSlugAnalyticsRoute
  '/publication/$slug/articles': typeof PublicationSlugArticlesRoute
  '/publication/$slug/subscribers': typeof PublicationSlugSubscribersRoute
  '/publication/$slug/writers': typeof PublicationSlugWritersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookmarks': typeof BookmarksRoute
  '/feed': typeof FeedRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/publication/$slug': typeof PublicationSlugRouteWithChildren
  '/writer/analytics': typeof WriterAnalyticsRoute
  '/writer/articles': typeof WriterArticlesRoute
  '/writer/dashboard': typeof WriterDashboardRoute
  '/writer/drafts': typeof WriterDraftsRoute
  '/writer/editor': typeof WriterEditorRoute
  '/writer/followers': typeof WriterFollowersRoute
  '/publication/$slug/analytics': typeof PublicationSlugAnalyticsRoute
  '/publication/$slug/articles': typeof PublicationSlugArticlesRoute
  '/publication/$slug/subscribers': typeof PublicationSlugSubscribersRoute
  '/publication/$slug/writers': typeof PublicationSlugWritersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/feed'
    | '/following'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/search'
    | '/settings'
    | '/trending'
    | '/article/$slug'
    | '/profile/edit'
    | '/publication/$slug'
    | '/writer/analytics'
    | '/writer/articles'
    | '/writer/dashboard'
    | '/writer/drafts'
    | '/writer/editor'
    | '/writer/followers'
    | '/publication/$slug/analytics'
    | '/publication/$slug/articles'
    | '/publication/$slug/subscribers'
    | '/publication/$slug/writers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/feed'
    | '/following'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/search'
    | '/settings'
    | '/trending'
    | '/article/$slug'
    | '/profile/edit'
    | '/publication/$slug'
    | '/writer/analytics'
    | '/writer/articles'
    | '/writer/dashboard'
    | '/writer/drafts'
    | '/writer/editor'
    | '/writer/followers'
    | '/publication/$slug/analytics'
    | '/publication/$slug/articles'
    | '/publication/$slug/subscribers'
    | '/publication/$slug/writers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/feed'
    | '/following'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/search'
    | '/settings'
    | '/trending'
    | '/article/$slug'
    | '/profile/edit'
    | '/publication/$slug'
    | '/writer/analytics'
    | '/writer/articles'
    | '/writer/dashboard'
    | '/writer/drafts'
    | '/writer/editor'
    | '/writer/followers'
    | '/publication/$slug/analytics'
    | '/publication/$slug/articles'
    | '/publication/$slug/subscribers'
    | '/publication/$slug/writers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookmarksRoute: typeof BookmarksRoute
  FeedRoute: typeof FeedRoute
  FollowingRoute: typeof FollowingRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TrendingRoute: typeof TrendingRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  PublicationSlugRoute: typeof PublicationSlugRouteWithChildren
  WriterAnalyticsRoute: typeof WriterAnalyticsRoute
  WriterArticlesRoute: typeof WriterArticlesRoute
  WriterDashboardRoute: typeof WriterDashboardRoute
  WriterDraftsRoute: typeof WriterDraftsRoute
  WriterEditorRoute: typeof WriterEditorRoute
  WriterFollowersRoute: typeof WriterFollowersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/publication/$slug': {
      id: '/publication/$slug'
      path: '/publication/$slug'
      fullPath: '/publication/$slug'
      preLoaderRoute: typeof PublicationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/analytics': {
      id: '/writer/analytics'
      path: '/writer/analytics'
      fullPath: '/writer/analytics'
      preLoaderRoute: typeof WriterAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/articles': {
      id: '/writer/articles'
      path: '/writer/articles'
      fullPath: '/writer/articles'
      preLoaderRoute: typeof WriterArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/dashboard': {
      id: '/writer/dashboard'
      path: '/writer/dashboard'
      fullPath: '/writer/dashboard'
      preLoaderRoute: typeof WriterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/drafts': {
      id: '/writer/drafts'
      path: '/writer/drafts'
      fullPath: '/writer/drafts'
      preLoaderRoute: typeof WriterDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/editor': {
      id: '/writer/editor'
      path: '/writer/editor'
      fullPath: '/writer/editor'
      preLoaderRoute: typeof WriterEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/followers': {
      id: '/writer/followers'
      path: '/writer/followers'
      fullPath: '/writer/followers'
      preLoaderRoute: typeof WriterFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publication/$slug/analytics': {
      id: '/publication/$slug/analytics'
      path: '/analytics'
      fullPath: '/publication/$slug/analytics'
      preLoaderRoute: typeof PublicationSlugAnalyticsRouteImport
      parentRoute: typeof PublicationSlugRoute
    }
    '/publication/$slug/articles': {
      id: '/publication/$slug/articles'
      path: '/articles'
      fullPath: '/publication/$slug/articles'
      preLoaderRoute: typeof PublicationSlugArticlesRouteImport
      parentRoute: typeof PublicationSlugRoute
    }
    '/publication/$slug/subscribers': {
      id: '/publication/$slug/subscribers'
      path: '/subscribers'
      fullPath: '/publication/$slug/subscribers'
      preLoaderRoute: typeof PublicationSlugSubscribersRouteImport
      parentRoute: typeof PublicationSlugRoute
    }
    '/publication/$slug/writers': {
      id: '/publication/$slug/writers'
      path: '/writers'
      fullPath: '/publication/$slug/writers'
      preLoaderRoute: typeof PublicationSlugWritersRouteImport
      parentRoute: typeof PublicationSlugRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface PublicationSlugRouteChildren {
  PublicationSlugAnalyticsRoute: typeof PublicationSlugAnalyticsRoute
  PublicationSlugArticlesRoute: typeof PublicationSlugArticlesRoute
  PublicationSlugSubscribersRoute: typeof PublicationSlugSubscribersRoute
  PublicationSlugWritersRoute: typeof PublicationSlugWritersRoute
}

const PublicationSlugRouteChildren: PublicationSlugRouteChildren = {
  PublicationSlugAnalyticsRoute: PublicationSlugAnalyticsRoute,
  PublicationSlugArticlesRoute: PublicationSlugArticlesRoute,
  PublicationSlugSubscribersRoute: PublicationSlugSubscribersRoute,
  PublicationSlugWritersRoute: PublicationSlugWritersRoute,
}

const PublicationSlugRouteWithChildren = PublicationSlugRoute._addFileChildren(
  PublicationSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookmarksRoute: BookmarksRoute,
  FeedRoute: FeedRoute,
  FollowingRoute: FollowingRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TrendingRoute: TrendingRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  PublicationSlugRoute: PublicationSlugRouteWithChildren,
  WriterAnalyticsRoute: WriterAnalyticsRoute,
  WriterArticlesRoute: WriterArticlesRoute,
  WriterDashboardRoute: WriterDashboardRoute,
  WriterDraftsRoute: WriterDraftsRoute,
  WriterEditorRoute: WriterEditorRoute,
  WriterFollowersRoute: WriterFollowersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
